x,y = 10,20
print(x,y)
print(x>y)
print(x<y)
print(x==y)
print(x!=y)
print(x>=y)
print(x<=y)
print(x and y)
print(x or y)
print(x>0 and y>0)
print(x>0 or y>0)
print(not (x >0 and y>0))
print (not (x>0 or y>0))
print(x is y)
print(x is not y)